Update train_and_evaluate_using_ray.md
tensortrade-org/tensortrade pull request #375
Opened 2022-01-16 16:54 UTC by Grahlus

evaluation.csv was not found because the actual directory changed during the run.
-> Added Get the current working directory and add it to csv_filename.

2022-01-21 00:20 UTC, carlogrisetti commented on docs/source/examples/train_and_evaluate_using_ray.md
> +    "csv_filename": cwd + "/training.csv"  # The variable that will be used to differentiate training and validation datasets
you should use the cross-platform way of doing this, with:
os.path.join(cwd, 'training.csv')

2022-01-21 00:20 UTC, carlogrisetti commented on docs/source/examples/train_and_evaluate_using_ray.md
> +    "csv_filename": cwd + "/evaluation.csv",  # The variable that will be used to differentiate training and validation datasets
you should use the cross-platform way of doing this, with:
os.path.join(cwd, 'evaluation.csv')

2022-01-21 00:21 UTC, carlogrisetti requested changes
Please switch to os.path.join instead of concatenating strings

2022-01-22 13:13 UTC, Grahlus commented
Changed to os.path.join

2022-01-22 21:50 UTC, merged

2022-01-22 21:50 UTC, carlogrisetti commented
Thanks!